spring.application.name=task-manager
 
# H2 Database
spring.datasource.url=jdbc:h2:mem:taskdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
 
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
 
# H2 Console
spring.h2.console.enabled=true
 
# Gemini Fake API Key 
gemini.api.key=AIzaSyCVKM8On1dEVR_mrsPQs2rNzV8Vzc2jPUY
